### ISSUE TITLE
Error en la imagen una vez terminado el tiempo de sesion de un usuario

### ISSUE THREAD

**Issue by emiarias** [ezeamin/rollingVet#1]
Luego de dejar una sesion abierta un tiempo x, se muestra perfecto la pantalla de indicando que su sesion fue finalizada pero la imagen aparece dañada

![image](https://user-images.githubusercontent.com/18445151/157338520-09db0b9b-2e77-4b15-bb83-7a13713f2934.png)

**Comment by ezeamin** [comment]
Eso ocurre porque la pagina esta siendo cargada desde el servidor (por los problemas que en el readme se detalla) y, al caerse el servidor o la conexion con el mismo, tampoco puede traer el recurso de la imagen
