### ISSUE TITLE
Agregar un monto maximo en los precios de los planes

### ISSUE THREAD

**Issue by emiarias** [ezeamin/rollingVet#3]
Al modificar el precio de un plan perfectamente no se puede agregar valores menores a 0, pero deberia tener un limite de monto maximo.

![image](https://user-images.githubusercontent.com/18445151/157342230-83f875e9-94b1-4f25-aec2-992b7ce329fb.png)

**Comment by ezeamin** [comment]
Corregido. El maximo ahora es 100.000
